### ISSUE TITLE
Add middleware to upload PDF

### ISSUE THREAD

**Issue by surya7765** [surya7765/shark-tank#2]
Just navigate through the application and add the functionality to upload PDF using any 3rd party library.

**Comment by AbhishekJadhav2002** [comment]
Hi @surya7765! I would like to work on this feature. Will you assign me ?

**Comment by surya7765** [comment]
> Hi @surya7765! I would like to work on this feature. Will you assign me ?

Yeah sure, Also give it a star.

**Comment by AbhishekJadhav2002** [comment]
@surya7765

## Question
### Where to save the PDF ?
- [x] In the server directory (`./uploads`) as a local file instance
- [x] In the database as binary buffer

**Comment by AbhishekJadhav2002** [comment]
> > Hi @surya7765! I would like to work on this feature. Will you assign me ?
> 
> Yeah sure, Also give it a star.

Can you label this issue for `hacktoberfest` ?

**Comment by surya7765** [comment]
> @surya7765
> 
> ## Question
> ### Where to save the PDF ?
> * [x]  In the server directory (`./uploads`) as a local file instance
> * [x]  In the database as binary buffer

Either of any

**Comment by surya7765** [comment]
Solved.
